
export const GET_MOVIE_DATA="GET_MOVIE_DATA";

export const GET_GENRE_DATA="GET_GENRE_DATA";

export const SUBMIT_GENRES="SUBMIT_GENRES";

export const SHOW_SUBMIT_GENRES="SHOW_SUBMIT_GENRES";

export const HIDE_SUBMIT_GENRES="HIDE_SUBMIT_GENRES";

export const MOVIE_LIST_DATA_LOADED="MOVIE_LIST_DATA_LOADED";

export const MOVIE_GENRES_DATA_LOADED="MOVIE_GENRES_DATA_LOADED";

export const API_ERRORED_MOVIE_LIST ="API_ERRORED_MOVIE_LIST";

export const API_ERRORED_GENRE_LIST ="API_ERRORED_GENRE_LIST";

export const APP_READY ="APP_READY";

export const ADD_GENRE = "ADD_GENRE";

export const FILTER_RATING = "FILTER_RATING";

export const SORT_POPULAR = "SORT_POPULAR";




